import Layout from "@/components/layout/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen bg-light">
        <Layout classname="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="profile picture"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2">
              <AnimatedText
                classname="text-6xl font-bold text-left"
                text="Turning Vision Into Reality With Code And Design. "
              />
              <p className="my-5">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center">
                <Link
                  className="flex p-2.5 px-6 bg-dark text-light rounded-lg text-lg font-semibold border-2 border-black hover:bg-light hover:text-dark"
                  href="/dummy.pdf"
                  target="_blank"
                  download={true}
                >
                  Resume <LinkArrow className="ml-2" />
                </Link>
                <Link
                  className="ml-4 text-lg font-semibold underline"
                  href="mailto:slobodjanik1997@gmail.com"
                  target="_blank"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
